import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Compass, Globe2, HeartHandshake, Plane } from 'lucide-react';

export default function HomePage(){return <main className="new-home">
<section className="new-hero" style={{background:'var(--blue)',backgroundImage:'none',minHeight:'620px'}}><div className="new-hero-content"><p className="eyebrow light">ADDIS ABABA · THE WORLD · YOUR WAY</p><h1>The world is waiting.<br/><em>Make it yours.</em></h1><p>Thoughtful travel planning from your first question to your flight home.</p><div className="new-hero-actions"><Link className="button gold" href="/contact">Plan your journey <ArrowUpRight size={18}/></Link><Link className="hero-text-link" href="/destinations">Explore destinations <ArrowRight size={18}/></Link></div></div><div className="new-hero-meta"><span>YOUR PATHWAY TO EXPLORATION</span><span>ROOTED IN ADDIS ABABA · CONNECTED TO THE WORLD</span></div></section>
<section className="home-intro container"><div><p className="eyebrow">TRAVEL, WITHOUT THE FRICTION</p><h2>More possibilities.<br/><em>Less to worry about.</em></h2></div><p>Flights, Umrah, visas, study abroad and tailor-made holidays — arranged locally, with personal attention and clear communication.</p></section>
<section className="home-services container"><Link href="/services"><span><Plane size={23}/><b>Flights & hotels</b><small>Domestic & international</small></span><ArrowUpRight/></Link><Link href="/services"><span><HeartHandshake size={23}/><b>Umrah journeys</b><small>Thoughtfully arranged</small></span><ArrowUpRight/></Link><Link href="/services"><span><Globe2 size={23}/><b>Visa assistance</b><small>Clear guidance</small></span><ArrowUpRight/></Link><Link href="/services"><span><Compass size={23}/><b>Tailor-made holidays</b><small>Built around you</small></span><ArrowUpRight/></Link></section>
<section className="home-feature"><div className="container home-feature-grid"><div><p className="eyebrow light">JOURNEYS WORTH TAKING</p><h2>Some places stay<br/><em>with you.</em></h2><p>Discover experiences across Ethiopia, the Gulf and beyond. Browse the journeys and start with a conversation.</p><Link className="button gold" href="/destinations">Explore destinations <ArrowRight size={18}/></Link></div><div className="feature-card"><Image src="/images/umrah.jpg" alt="Pilgrimage journey" fill/><div><span>FEATURED JOURNEY</span><strong>Makkah & Madinah</strong><small>Umrah · 14 days</small></div></div></div></section>
<section className="home-trust container"><div><p className="eyebrow">LOCAL KNOWLEDGE. PERSONAL SERVICE.</p><h2>Wherever you're going,<br/><em>start here.</em></h2></div><div><p>Based at Garad Building in Welo Sefer, Addis Ababa, our team helps turn plans into practical journeys.</p><Link className="text-link blue" href="/about">Meet ANAN TRAVEL <ArrowUpRight size={17}/></Link></div></section>
<section className="home-cta"><div className="container"><p className="eyebrow light">READY WHEN YOU ARE</p><h2>Let’s plan<br/><em>something.</em></h2><Link className="button gold" href="/contact">Talk to our team <ArrowUpRight size={18}/></Link></div></section>
</main>}
