'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {ArrowUpRight,ArrowRight,Plane,Globe2,MapPin,Phone,Compass,GraduationCap,CalendarDays,HeartHandshake,Check,MessageCircle,ShieldCheck} from 'lucide-react';
import destinations from './destinations.json';
import {translations} from './translations';
const wa=(text:string)=>`https://wa.me/251960555000?text=${encodeURIComponent(text)}`;
const services=[
 {icon:Plane,title:'Flights & hotels',text:'Domestic and international flights, considered connections and somewhere special to stay. Arrange your journey locally in Ethiopian Birr.',tag:'THE WORLD, WITHIN REACH'},
 {icon:HeartHandshake,title:'Umrah journeys',text:'A meaningful journey, thoughtfully arranged. Visa assistance, flights, Makkah and Madinah accommodation, and dedicated group support.',tag:'TRAVEL WITH PURPOSE'},
 {icon:Globe2,title:'Visa assistance',text:'Clear guidance for tourist, business and student visa applications, with a careful review of your documentation.',tag:'CLARITY AT EVERY STEP'},
 {icon:CalendarDays,title:'Embassy appointments',text:'Help navigating appointment portals and preparing for US, UK and Schengen interviews. Availability and decisions remain with the embassy.',tag:'PREPARED, NOT OVERWHELMED'},
 {icon:GraduationCap,title:'Study abroad',text:'From university applications to student visa preparation, personal guidance for opportunities in Europe, Asia, the USA and Canada.',tag:'A NEW CHAPTER'},
 {icon:Compass,title:'Tailor-made holidays',text:'Discover Lalibela, Gondar, Aksum, the Simien Mountains and the Omo Valley, with a journey shaped around your interests and pace.',tag:'FOLLOW YOUR CURIOSITY'}
];
const packages=[{name:'A journey of devotion',place:'Makkah & Madinah',type:'UMRAH · 14 DAYS',image:'umrah',price:'150,000',details:['Return flight from Addis Ababa','Umrah visa & insurance','Hotel near the Haram','Group transport & guidance']},{name:'A different kind of skyline',place:'Dubai, United Arab Emirates',type:'CITY ESCAPE · FLIGHT + VISA',image:'dubai',price:'95,000',details:['Return flight from Addis Ababa','Tourist visa assistance','Airport transfer','Optional hotel arrangements']},{name:'Discover a new perspective',place:'Riyadh, Saudi Arabia',type:'SAUDI ARABIA · 7 NIGHTS',image:'hero',price:'110,000',details:['Return flight from Addis Ababa','Visa assistance','Seven nights’ accommodation','Local support & SIM card']}];
const faqs=[['Can I pay in Ethiopian Birr?','Yes. Our team can arrange flights, hotels and travel packages with payment in Ethiopian Birr. Your written quote will confirm the amount, available payment methods and terms before you commit.'],['How does booking work?','Send your destination, dates and preferences through WhatsApp, or visit our office. We will review availability and prepare a quote. Your enquiry does not charge you or confirm a booking.'],['Can you guarantee a visa or appointment?','Visa decisions and appointment availability are controlled by the relevant authorities. We help you understand the process, prepare documentation and review the next steps if an application is refused.'],['What is included in the Umrah package?','The supplied package includes return flights, visa and insurance, accommodation near the Haram, group transport and guidance. Meals and personal expenses are separate unless your written quote includes them.'],['How long will my visa take?','Processing depends on the destination, application and appointment availability. Ask our team to review the current requirements for your trip before making non-refundable arrangements.'],['Do I need to visit your office?','You can begin on WhatsApp at +251 960 555 000. You are also welcome at Garad Building, Welo Sefer, Addis Ababa, Monday–Friday 8:30 AM–6:00 PM or Saturday 9:00 AM–3:00 PM.']];
export default function TravelSite(){
 const [menu,setMenu]=useState(false);const [lang,setLang]=useState<'en'|'am'|'om'>('en');const [tab,setTab]=useState('Flights');const [sent,setSent]=useState(false);const t=translations[lang];
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 function enquire(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const lines=Array.from(data.entries()).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`);window.open(wa(`Hello ANAN TRAVEL, I would like help with ${tab}.\n${lines.join('\n')}`),'_blank','noopener,noreferrer');setSent(true)}
 return <>
 <a className="skip" href="#main">Skip to content</a>
 <header className="header"><a className="brand" href="#home" aria-label="ANAN TRAVEL home">ANAN TRAVEL<span className="brand-star">✦</span><small>YOUR PATHWAY TO EXPLORATION</small></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#booking">{t.navHome}</a><a href="#services">{lang==='en'?'Services':t.navServices}</a><a href="#packages">{t.navDestinations}</a><a href="#faq">{t.navContact}</a></nav><div className="header-actions"><label className="language"><span className="sr-only">Language for introduction and booking</span><select value={lang} onChange={e=>setLang(e.target.value as typeof lang)}><option value="en">EN</option><option value="am">አማ</option><option value="om">OM</option></select></label><a className="button header-cta" href="#booking">Plan your journey <ArrowUpRight size={16}/></a><button className={`hamburger ${menu?'open':''}`} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}><span/><span/><span/></button></div><nav id="mobile-nav" className="mobile-nav" hidden={!menu} aria-label="Mobile navigation">{[['booking','Plan your journey'],['services','Our services'],['packages','Experiences'],['about','About ANAN TRAVEL'],['faq','Help & FAQ'],['contact','Contact']].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={18}/></a>)}</nav></header>
 <main id="main"><section className="hero" id="home"><Image src="/images/hero.jpg" alt="Airplane wing above the clouds in warm evening light" fill priority sizes="100vw" className="hero-image"/><div className="hero-shade"/><div className="hero-content container" lang={lang}><p className="eyebrow light">ADDIS ABABA. THE WORLD. YOUR WAY.</p><h1>{lang==='en'?<>The world is waiting.<br/><em>Make it yours.</em></>:t.heroTitle}</h1><p className="hero-copy">{lang==='en'?'Extraordinary places. Meaningful journeys. From your first question to your flight home, we take care of the details.':t.heroDesc}</p><div className="hero-buttons"><a className="button gold" href="#booking">{lang==='en'?'Find your next journey':t.navHome}<ArrowUpRight size={18}/></a><a className="text-link" href="#packages">Explore our experiences <ArrowRight size={18}/></a></div></div><div className="hero-bottom container"><span>YOUR PATHWAY TO EXPLORATION</span><span><MapPin size={14}/> Rooted in Addis Ababa. Connected to the world.</span><a href="#booking" aria-label="Scroll to plan your journey">SCROLL TO DISCOVER ↓</a></div></section>
 <section className="booking container" id="booking" aria-labelledby="booking-title"><div className="booking-heading"><div><p className="eyebrow">LET’S BEGIN</p><h2 id="booking-title">Where will you go next?</h2></div><p>Tell us your plans. We’ll take it from here.</p></div><div className="booking-tabs" aria-label="Enquiry type">{[['Flights',Plane,t.tabFlights],['Visa services',Globe2,t.tabVisa],['Holidays',Compass,t.tabTours]].map(([name,Icon,label])=>{const I=Icon as typeof Plane;return <button key={String(name)} type="button" aria-pressed={tab===name} className={tab===name?'selected':''} onClick={()=>{setTab(String(name));setSent(false)}}><I size={18}/>{String(label)}</button>})}</div><form key={tab} onSubmit={enquire} className="booking-form"><label>{tab==='Flights'?t.lblFrom:'Your name'}<input name={tab==='Flights'?'From':'Name'} defaultValue={tab==='Flights'?'Addis Ababa (ADD)':''} placeholder="Full name" required maxLength={100}/></label><label>{t.lblDest}{tab==='Flights'?<select name="Destination" required defaultValue=""><option value="" disabled>Select your destination</option>{destinations.map(x=><option key={x}>{x}</option>)}</select>:<input name="Destination" placeholder={tab==='Holidays'?'e.g. Lalibela, Ethiopia':'e.g. United Arab Emirates'} required maxLength={100}/>}</label><label>Travel date<input type="date" name="Travel date" required/></label><label>{t.lblPhone}<input type="tel" name="Phone" placeholder="+251 …" required autoComplete="tel" minLength={7} maxLength={25}/></label><button className="button" type="submit">Request a quote <ArrowUpRight size={18}/></button><p className="form-note">Opens WhatsApp with your details. Send your message there to start your enquiry. No payment required.</p>{sent&&<p className="form-feedback" role="status">Your enquiry is ready in WhatsApp. Please send it there. If WhatsApp did not open, <a href={wa('Hello ANAN TRAVEL, I would like a travel quote.')} target="_blank" rel="noopener noreferrer">open our chat</a> or call <a href="tel:+251960555000">+251 960 555 000</a>.</p>}</form></section>
 <div className="trust-strip container"><span>PERSONAL SERVICE.<br/><b>EVERY STEP OF THE WAY.</b></span><p><MapPin/>Addis Ababa based</p><p><HeartHandshake/>Pay locally in ETB</p><p><Globe2/>Domestic & international</p><p><MessageCircle/>A real person to help</p></div>
 <section className="section container" id="services"><div className="section-heading"><div><p className="eyebrow">THOUGHTFULLY ARRANGED</p><h2>More possibilities.<br/><em>Less to worry about.</em></h2></div><p>A pilgrimage. A new beginning. A well-earned escape.<br/>Whatever takes you there, we help make the journey feel effortless.</p></div><div className="services-grid">{services.map(({icon:Icon,title,text,tag},i)=><article className="service" key={title}><div className="service-top"><Icon size={26} strokeWidth={1.4}/><span>0{i+1}</span></div><p className="eyebrow">{tag}</p><h3>{title}</h3><p>{text}</p><a href={wa(`Hello ANAN TRAVEL, please tell me more about ${title}.`)} target="_blank" rel="noopener noreferrer" aria-label={`Enquire about ${title}`}>Let’s talk <ArrowUpRight size={18}/></a></article>)}</div></section>
 <section className="experiences section" id="packages"><div className="container"><div className="section-heading"><div><p className="eyebrow">JOURNEYS WORTH TAKING</p><h2>Some places stay<br/><em>with you.</em></h2></div><p>Three ways to begin your next chapter.<br/>Every package can start with a conversation.</p></div><div className="package-grid">{packages.map(p=><article className="package" key={p.name}><div className="package-image"><Image src={`/images/${p.image}.jpg`} alt={p.image==='hero'?'A flight above the clouds':p.place} fill sizes="(max-width: 720px) 100vw, 33vw"/><span>{p.type}</span></div><div className="package-body"><p className="place"><MapPin size={13}/>{p.place}</p><h3>{p.name}</h3><ul>{p.details.map(d=><li key={d}><Check size={14}/>{d}</li>)}</ul><div className="package-bottom"><div><small>Indicative price from</small><strong>{p.price} <span>ETB</span></strong></div><a href={wa(`Hello ANAN TRAVEL, please send a current quote for ${p.name} — ${p.place}.`)} target="_blank" rel="noopener noreferrer" className="enquire" aria-label={`Enquire about ${p.place}`}><ArrowUpRight size={22}/></a></div></div></article>)}</div><p className="price-note">Guide prices from the supplied package list, per person. Availability, inclusions and current pricing are confirmed in your written quote.</p></div></section>
 <section className="about section container" id="about"><div className="about-title"><p className="eyebrow">A LOCAL TEAM. A PERSONAL CONNECTION.</p><h2>Your journey.<br/>Our <em>attention<br/>to detail.</em></h2><a className="text-link blue" href="#contact">Meet us in Addis Ababa <ArrowUpRight size={18}/></a></div><div className="about-copy"><p className="intro">Good travel begins with someone who listens.</p><p>At ANAN TRAVEL, based at Garad Building in Welo Sefer, we bridge the gap between your travel dreams and the details that make them possible.</p><p>International bookings, unfamiliar paperwork and foreign currency payments can feel complicated. Our team helps you navigate the process locally, so you can focus on what lies ahead.</p><div className="values"><div><HeartHandshake/><h3>Personal, from the start</h3><p>Plans built around your purpose, preferences and budget.</p></div><div><ShieldCheck/><h3>Clarity before commitment</h3><p>Written quotes and a conversation about what is included.</p></div></div></div></section>
 <section className="support-band"><div className="container support-inner"><div><p className="eyebrow light">ALREADY PLANNING YOUR DEPARTURE?</p><h2>A little reassurance<br/>goes a long way.</h2></div><div><p>Need to check your flight, discuss baggage or change your plans? Share your flight number and travel date with our team for assistance.</p><a className="button gold" href={wa('Hello ANAN TRAVEL, I need assistance checking my flight. Flight number: ... Travel date: ...')} target="_blank" rel="noopener noreferrer">Ask about your flight <Plane size={18}/></a></div></div></section>
 <section className="section container" id="testimonials"><div className="section-heading"><div><p className="eyebrow">THE PEOPLE BEHIND THE JOURNEYS</p><h2>Travel is personal.<br/><em>So are the stories.</em></h2></div><p>Client stories supplied by ANAN TRAVEL.</p></div><div className="quotes">{[['“ANAN TRAVEL handled our entire Umrah trip — visa, flights, hotels in Makkah and Madinah. Everything was perfect and we paid in Birr.”','Fatuma A.','Umrah pilgrim · Addis Ababa'],['“ANAN TRAVEL guided me through every document — bank statements, cover letter, everything. Professional and honest team.”','Biruk T.','UAE visa client · Dire Dawa'],['“My daughter is now studying in Turkey thanks to ANAN TRAVEL’s education consultancy. They handled the university application, student visa, and even embassy preparation.”','Meron G.','Education client · Addis Ababa']].map(([q,n,d])=><figure key={n}><span className="quote-mark" aria-hidden="true">“</span><blockquote>{q}</blockquote><figcaption><span className="avatar">{n[0]}</span><div><b>{n}</b><small>{d}</small></div></figcaption></figure>)}</div></section>
 <section className="faq-section section" id="faq"><div className="container faq-layout"><div><p className="eyebrow">A FEW THINGS TO KNOW</p><h2>Before<br/><em>you set off.</em></h2><p>Still have a question? We’re here.</p><a className="text-link blue" href={wa('Hello ANAN TRAVEL, I have a question.')} target="_blank" rel="noopener noreferrer">Talk to our team <ArrowUpRight size={18}/></a></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
 <section className="section container contact" id="contact"><div><p className="eyebrow">COME SAY HELLO</p><h2>Let’s plan<br/><em>something.</em></h2></div><div><p>Garad Building, Welo Sefer<br/>Addis Ababa, Ethiopia</p><p>Monday–Friday 8:30 AM–6:00 PM<br/>Saturday 9:00 AM–3:00 PM</p><a className="button" href={wa('Hello ANAN TRAVEL, I would like to plan a journey.')} target="_blank" rel="noopener noreferrer">Chat on WhatsApp <MessageCircle size={18}/></a></div></section>
 </main><footer className="footer"><div className="container footer-main"><div><a className="brand footer-brand" href="#home">ANAN TRAVEL<small>YOUR PATHWAY TO EXPLORATION</small></a><p>Thoughtful travel planning from Addis Ababa to the world.</p></div><div><p className="eyebrow light">CONTACT</p><a href="tel:+251960555000">+251 960 555 000</a><a href={wa('Hello ANAN TRAVEL, I would like to chat with your team.')} target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="mailto:info@anantravel.com">info@anantravel.com</a></div><div><p className="eyebrow light">EXPLORE</p><a href="#services">Our services</a><a href="#packages">Experiences</a><a href="#faq">Help & FAQ</a></div></div><div className="container footer-legal"><span>© {new Date().getFullYear()} ANAN TRAVEL. All rights reserved.</span></div></footer>
 </>;
}